[package]
name = "fastnode-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Benchmarks for fastnode"

[dev-dependencies]
criterion.workspace = true
fastnode-util.workspace = true
tempfile.workspace = true

[[bench]]
name = "hashing"
harness = false
