apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground
  namespace: howth-playground
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - run.howth.run
      secretName: playground-tls
  rules:
    - host: run.howth.run
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: playground
                port:
                  number: 80
